### ISSUE TITLE
Package size exceeded the configured limit of 50 MB

### ISSUE THREAD

**Issue by andrepgaspar** [Lateralus138/blackhosts#1] opened 2022-05-18 10:44 UTC
when i run blackhosts in terminal with fakenews and gambling options

the hosts file that is saved only says this

"Package size exceeded the configured limit of 50 MB. Try https://github.com/StevenBlack/hosts/tree/master/alternates/gambling-fakenews/hosts instead."

i'm on macos if helps

**Comment by Lateralus138** [comment] 2022-05-18 12:11
No idea, but I will try and look into it in the next couple of days. I don't have MacOs (I use this in Windows and Linux) and so I have to set up a testing CI here at GH. I'm fairly sure none of the hosts files that this tool can retrieve are anywhere near that size (although I haven't checked Fake News yet).

Thanks for the issue though, sorry you're having trouble, but I've had no feedback on the MacOs version so it's good to hear from that world.

I'll set up a test today or tomorrow and probably get back to you in a couple of days.

**Comment by Lateralus138** [comment] 2022-05-18 22:12
I ran a test ***[here](https://github.com/Lateralus138/macostests/runs/6497764606?check_suite_focus=true)*** (click the 'Make MacOs' section, might take a minute to load) and I **can't** reproduce this issue.

The tests ran are:
`./blackhosts --help` - just to make sure it works at all
`sudo ./blackhosts fakenews-gambling -y` - update the hosts file
`cat /private/etc/hosts` - check the contents of the new hosts file

The above test were successful and affirmed (for me at least) that it works in MacOS.

Would you post the steps you took to reproduce this? Should only need to run `sudo blackhosts` (possibly with -y) so I assume that's what you did (though I doubt your steps pertain to this issue, I just want to cover all bases).

**Comment by andrepgaspar** [comment] 2022-05-19 15:49
Alright, did some more tests, the command "sudo blackhosts fakenews-gambling -y" gives no problem at all
but if you change order and do "sudo blackhosts gambling-fakenews -y" you get the issue I said

EDIT: further examination into StevenBlack repo, it's his problem not yours, he only has this specific package if you start with fakenews and not gambling

**Comment by Lateralus138** [comment] 2022-05-19 16:16
Yes, that's because there isn't a folder named that in the alternates folder of [Steven's](https://github.com/StevenBlack/hosts/tree/master/alternates) repository; `gambling-fakenews` is not an option. These are your possible options:
![Possible Alternate Options](https://user-images.githubusercontent.com/21045862/169347628-587ff9f7-fc58-43fa-be40-16dda2025829.png)

Thanks for this issue though, even though it didn't turn out to be anything you got me motivated and on task of checking if it actually works in MacOS or not and I'm happy it does.

Closing.

Edit: This is not an issue at Steven's repo, he can name the folders anything he likes.

**Closed as completed** 2022-05-19 16:16 UTC
